# These are supported funding model platforms
patreon: https://patreon.com/RocketCityDynamics388?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link

